# Generated by Django 4.1.1 on 2023-06-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
